services:
  postgres-user:
    image: postgres:17
    container_name: pollenaware-user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pollenaware_users
      POSTGRES_USER: pollenaware
      POSTGRES_PASSWORD: YOUR_PASSWORD
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: pollenaware-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: pollenaware
      RABBITMQ_DEFAULT_PASS: pollenaware

volumes:
  user_postgres_data:
