services:
  postgres-user:
    image: postgres:17
    container_name: pollenaware-user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pollenaware_users
      POSTGRES_USER: pollenaware
      POSTGRES_PASSWORD: YOUR_PASSWORD
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: pollenaware-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: pollenaware
      RABBITMQ_DEFAULT_PASS: pollenaware

  postgres-auth:
    image: postgres:17
    container_name: pollenaware-auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pollenaware_auth
      POSTGRES_USER: pollenaware
      POSTGRES_PASSWORD: pollenaware_dev
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  postgres-environmental:
    image: postgres:17
    container_name: pollenaware-environmental-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: pollenaware_environmental
      POSTGRES_USER: pollenaware
      POSTGRES_PASSWORD: pollenaware_dev
    volumes:
      - environmental_postgres_data:/var/lib/postgresql/data

  postgres-risk:
    image: postgres:17
    container_name: pollenaware-risk-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: pollenaware_risk
      POSTGRES_USER: pollenaware
      POSTGRES_PASSWORD: pollenaware_dev
    volumes:
      - risk_postgres_data:/var/lib/postgresql/data

volumes:
  user_postgres_data:
  auth_postgres_data:
  environmental_postgres_data:
  risk_postgres_data:
