name: Feature
description: New feature
title: "[FEATURE] "
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
